name: Deploy Flutter Web to Firebase Hosting

on:
  push:
    branches:
      - main  # Cambia 'main' por la rama que deseas monitorear

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout el código del repositorio
      - name: Checkout code
        uses: actions/checkout@v3

      # 2. Instalar Node.js
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '22'

      # 3. Instalar dependencias
      - name: Install dependencies
        run: npm ci

      # 4. Construir el proyecto
      - name: Build project
        run: npm run build

      # 5. Instalar Firebase CLI
      - name: Install Firebase CLI
        run: npm install -g firebase-tools

      # 6. Desplegar en Firebase Hosting
      - name: Deploy to Firebase Hosting
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN_PROD }}
        run: firebase deploy --only hosting:gloriafinance
